{
 "title": "Geo Service Dashboard",
 "tags": [ "geoservice" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Время ответа эндпоинтов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(geoservice_endpoint_duration_seconds_sum[5m]) / rate(geoservice_endpoint_duration_seconds_count[5m])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Количество запросов в секунду",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(geoservice_endpoint_requests_total[5m])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Время ответа внешнего API",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(geoservice_external_api_duration_seconds_sum[5m]) / rate(geoservice_external_api_duration_seconds_count[5m])",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}